### PR TITLE
provide 3.0.0-RC.18-7774d30 version

### PR DESCRIPTION
**Pull request by fkoehler**

### CODE REVIEW

**Comment by jamesward** [comment]
Is there a tagged release for what you need?

**Comment by fkoehler** [comment]
Nope, that's way I added the sha1 for it. If the tag is strictly required I guess we need to wait for the next one.

**Comment by jamesward** [comment]
I'd rather wait for a new release since adding sha1 releases makes the version listing less usable.  Can you check with the project and see how soon that will be?  If soon-ish then lets wait.  If not, then we can do a non-tag based release.

**Comment by fkoehler** [comment]
Looks like they are pretty active and it will be released soon. Let's wait for the next release than!

**Comment by jamesward** [comment]
Cool. Feel free to keep this open and update it when a new release comes out. Just add a comment here when you do that.

**Comment by nameetpai** [comment]
Submitted a PR for RC 19: https://github.com/webjars/ui-grid/pull/6

**Comment by jamesward** [comment]
Thanks! Closing this one.

**Pull request closed without merging**
